### ISSUE TITLE
CMS 5.2.0-beta1. Regression test: Calling `get_class()` without arguments is deprecated

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-versionfeed#102]
## Description
Test is failed because of Server Error `Calling get_class() without arguments is deprecated`. It's failed only in PHP 8.3 environment. 
**Executed on:**  SC PHP 8.3 Firefox sink
**Test failed:**  https://studio.cucumber.io/projects/301855/test-runs/946350/folder-snapshots/11133993/scenario-snapshots/34725739/test-snapshots/46397535

<img width="1439" alt="Screenshot_2024-03-12_at_2 08 22 PM (1)" src="https://github.com/silverstripe/silverstripe-versionfeed/assets/87288324/35d5923d-525d-435b-94ec-80b7709ff801">

## Acceptance criteria
- All instances of `get_class()` being called without a parameter in the sink are updated to avoid deprecation warnings.
- Update the changelog which currently says no code changes were required to add PHP 8.3 support.

## PRs
- https://github.com/silverstripe/silverstripe-versionfeed/pull/103
- https://github.com/silverstripe/silverstripe-documentconverter/pull/73
- https://github.com/silverstripe/developer-docs/pull/483

**Comment by maxime-rainville** [comment]
There's 4 instances that I could find

![image](https://github.com/silverstripe/silverstripe-versionfeed/assets/1168676/123b37ce-4997-4185-9f4b-825385e1dc14)
