### ISSUE TITLE
VersionFeed_Controller returns invalid HTML

### ISSUE THREAD

**Issue by torleif** [silverstripe-labs/silverstripe-versionfeed#16]
Line 161 in **VersionFeed_Controller.php**:
```
    Requirements::insertHeadTags(
			'<link rel="alternate nofollow" type="application/rss+xml" title="' . $title .
			'" href="' . $url . '" />');
```

According to w3:

```Bad value alternate nofollow for attribute rel on element link: The string nofollow is not a registered keyword.```

According to the registered link type extensions: http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions

**nofollow** is not a valid extension.

**Comment by tractorcow** [comment]
True, but google supports rel=nofollow, so for the forseeable future it's likely to remain in place. https://support.google.com/webmasters/answer/96569?hl=en

**Comment by tractorcow** [comment]
Closing this until we decide to change our mind. :)
