### ISSUE TITLE
TypeError is triggered when element being compared has a NULL title or Content

### ISSUE THREAD

**Issue by alex-dna** [silverstripe-labs/silverstripe-versionfeed#95]
### Module version(s) affected

3

### Description

When a record is saved without a title or content, when viewing the RSS changes feed, a type error occurs.

Uncaught TypeError: SilverStripe\View\Parsers\HtmlDiff::compareHtml(): Argument #1 ($from) must be of type array|string, null given, called in /var/www/html/vendor/silverstripe/versionfeed/src/VersionFeed.php on line 110

### How to reproduce

I first encountered the issue with Elemental, after saving an element without a title.
But it should be the case for any page too (although it is less likely to save a page without title through the CMS).
Easiest way to reproduce is to temper with database if possible, set a page record version title or content to NULL, then visit the page URL/changes.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-versionfeed/pull/96

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions.
